// Global imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// local imports
import './globals.css'
import ClientOnly from '@/components/ClientOnly'
import { ModalProvider } from '@/providers/modalProvider'
import ToasterProvider from '@/providers/ToasterProvider'
import AuthContextProvider from '@/providers/AuthContextProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Admin Panel',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <AuthContextProvider><html lang="en">
            <body className={inter.className}>
                
                <ClientOnly>
                    <ToasterProvider />
                    <ModalProvider />
                    {children}
                </ClientOnly>
            
            </body>
            </html >
        </AuthContextProvider>
    )
}
